export const SAVE_DATEBYSELECT = 'SAVE_DATEBYSELECT'
export const LOADING_TRUEDATEBYSELECT = 'LOADING_TRUEDATEBYSELECT'
export const LOADING_FALSEDATEBYSELECT = 'LOADING_FALSEDATEBYSELECT'
export const DELETE_ALLDATEBYSELECT = 'DELETE_ALLDATEBYSELECT'